### ISSUE TITLE
Weird SenseAir S8 CO2 response

### ISSUE THREAD

**Issue by krupis** [SFeli/ESP32_S8#4]
Hello. I try to use your library with the SenseAir S8 sensor. It seems to work fine (The sensor is responding to UART commands), but it returns weird CO2 values:

```
[1B][0;32mI (24032) Info: ABC-Period 180 [1B][0m
[1B][0;32mI (28032) Info: Firmware: 335 [1B][0m
[1B][0;32mI (32032) Info: Sensor-ID 793 [1B][0m
[1B][0;32mI (36032) Info: Sensor-ID 11344 [1B][0m
Sending data 
Response[0] = fe 
Response[1] = 04 
Response[2] = 02 
Response[3] = 22 
Response[4] = c3 
Response[5] = f5 
Response[6] = d5 
[1B][0;32mI (37082) Receive_TASK: CO2 8899 [1B][0m
Sending data 
Response[0] = fe 
Response[1] = 04 
Response[2] = 02 
Response[3] = 22 
Response[4] = bf 
Response[5] = f4 
Response[6] = 34 
[1B][0;32mI (42082) Receive_TASK: CO2 8895 [1B][0m
```

The returned values are way above the range of this sensor. From the datasheet, it says that this sensor is capable of measuring 400-2000ppm

**Comment by SFeli** [comment]
Hello 
can it be that you need to calibrate your S8-Sensor? In Document https://rmtplusstoragesenseair.blob.core.windows.net/docs/publicerat/PSP0113.pdf it suggest to shortcut Pin bCAL_in with G0 (Ground) for min 4 max 8 seconds.
A reboot does well :-)
One note appart : If you use Visual Studio Code with plattformio the parameter : monitor_filters = direct in platformio.ini will interpret the [xy - information.
Will keep the issue open for another 2 weeks and would be glad to get your findings. :-)

**Comment by krupis** [comment]
Thanks for a quick response. I did manual calibration (shorting bCal_in to gnd for about 6 seconds and I can confirm that readings went down to 400ppm.

It is quite strange why I had to do this since SenseAir say all their sensors come calibrated.


Anyways, how can I ensure the CO2 level that i calibrated the sensor on is really 400 ppm? I cant really ensure that so the readings might be faulty now. I did my calibration in my open air balcony but I dont know the actual CO2 levels here.

**Comment by SFeli** [comment]
Hi, 
you have done the best calibration you can do. To set the sensot to 400 ppm is to only possibility to influence the sensor. 
In the internet you can check the CO2 - Value on your place - perhaps you make the calibration on days where the CO2-Concentration on your place is low.

There is also another routine on the Sensor (ABC) which calibrates the sensor more or less automatic. very 180 hours it checks the values and reduces the baseline by 50 if not touched the 400 ppm. Most of the developer disable this routine. 

Will close your issue since the code works.

**Comment by SFeli** [comment]
Code works -
